# -*- coding: utf-8 -*-
"""Day 3 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1URhXmSA2SvBs7_KzqnnTpOWV0EQsQyv8
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

fmri=sns.load_dataset('fmri')
fmri.head()

sns.relplot(x='timepoint',y='signal',data=fmri)

sns.relplot(x='timepoint',y='signal',data=fmri,hue='subject')

sns.relplot(x='timepoint',y='signal',kind='line',data=fmri)

sns.relplot(x='timepoint',y='signal',kind='line',data=fmri,hue='subject')

sns.catplot(x='timepoint',y='region',kind='box',data=fmri)

sns.catplot(x='timepoint',y='region',kind='box',data=fmri,hue='subject')